name: dino_plus
description: A colorful rage runner with volcanoes and meteors
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.32.0
  flame_audio: ^2.10.4
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
  assets:
    -  assets/images/
